spring:

  application:
    name: aegiscode

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: false

  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY}
      chat:
        options:
          model: llama-3.3-70b-versatile # Modelo LLaMA 3 de 70B, ideal para análisis de código
          temperature: 0.1


app:
  vcs:
    github:
      token: ${TOKEN:fallback-local-token}