spring:
  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.eu-madrid-3.oraclecloud.com))(connect_data=(service_name=g8e9a9b11878921_aegiscodedb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: ${ORACLE_USER}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

  flyway:
    enabled: false

  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY}
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.1

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace