spring:
  datasource:
    url: jdbc:oracle:thin:@aegiscode_high?TNS_ADMIN=C:/Users/jlcastrom/Documents/WorkspaceIntelliJ/Shift-Left/infra/oracle-wallet
    username: ${ORACLE_USER}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver



    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false


  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY}
      chat:
        options:
          model: llama-3.3-70b-versatile # Modelo LLaMA 3 de 70B, ideal para análisis de código
          temperature: 0.1
