CREATE TABLE IF NOT EXISTS vulnerabilities (
                                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               scan_id VARCHAR(36) NOT NULL,
    cwe_id VARCHAR(50) NOT NULL,
    severity INT NOT NULL,
    description CLOB,
    remediation_patch CLOB,
    CONSTRAINT fk_audit_report
    FOREIGN KEY (scan_id)
    REFERENCES audit_reports(scan_id)
    ON DELETE CASCADE
    );

CREATE INDEX IF NOT EXISTS idx_vulnerabilities_scan_id ON vulnerabilities(scan_id);