-- 1. Crear la tabla relacional de vulnerabilidades vinculada a audit_reports
CREATE TABLE vulnerabilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id VARCHAR(36) NOT NULL,
    cwe_id VARCHAR(50) NOT NULL,
    severity INT NOT NULL,
    description TEXT,
    remediation_patch TEXT,
    CONSTRAINT fk_audit_report
        FOREIGN KEY (scan_id)
            REFERENCES audit_reports(scan_id)
            ON DELETE CASCADE
);

-- 2. Índice para optimizar las búsquedas por scan_id en los joins de Hibernate
CREATE INDEX idx_vulnerabilities_scan_id ON vulnerabilities(scan_id);

-- ============================================
-- Row Level Security (RLS) - Solo para PostgreSQL
-- ============================================
-- NOTA: Las siguientes políticas solo se aplican en producción (PostgreSQL/Supabase).
-- H2 no soporta RLS, pero no es necesario en desarrollo local.
--
-- En producción (PostgreSQL), ejecutar manualmente:
-- 1. ALTER TABLE vulnerabilities ENABLE ROW LEVEL SECURITY;
-- 2. DROP POLICY IF EXISTS deny_anon_vulnerabilities ON vulnerabilities;
-- 3. CREATE POLICY deny_anon_vulnerabilities ON vulnerabilities FOR ALL TO anon, authenticated USING (false);
